-- MySQL Script generated by MySQL Workbench
-- jue 26 may 2022 22:47:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema social_media
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `social_media` ;

-- -----------------------------------------------------
-- Schema social_media
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_media` ;
USE `social_media` ;

-- -----------------------------------------------------
-- Table `social_media`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_media`.`users` ;

CREATE TABLE IF NOT EXISTS `social_media`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `nick` VARCHAR(30) NOT NULL,
  `pass` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `age` DECIMAL(3,0) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_media`.`posts` ;

CREATE TABLE IF NOT EXISTS `social_media`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `text` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `social_media`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`user_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_media`.`user_post` ;

CREATE TABLE IF NOT EXISTS `social_media`.`user_post` (
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `post_id`),
  INDEX `fk_user_has_post_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_user_has_post_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `social_media`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `social_media`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`post_has_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_media`.`post_has_post` ;

CREATE TABLE IF NOT EXISTS `social_media`.`post_has_post` (
  `post_id` INT NOT NULL,
  `post_id1` INT NOT NULL,
  PRIMARY KEY (`post_id`, `post_id1`),
  INDEX `fk_post_has_post_post2_idx` (`post_id1` ASC) VISIBLE,
  INDEX `fk_post_has_post_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_post_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `social_media`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_post_post2`
    FOREIGN KEY (`post_id1`)
    REFERENCES `social_media`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
